In [1]:
import numpy as np

# Stack

Join a sequence of arrays _**along a new axis**_.

In [2]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a,"\n",b)

[1 2 3 4] 
 [5 6 7 8]


In [22]:
print(a.ndim)   #1 dimensionlılar.
print(b.ndim)

1
1


Normalde bunları birbirine farklı dimension yaratarak ekleyemezsin **concatenate** kullanarak.

Gördüğümüz gibi hata alıyoruz.

In [23]:
np.concatenate([a,b], axis = 1) #axis 1 is out of bounds for array of dimension 1

AxisError: axis 1 is out of bounds for array of dimension 1

Ama stackle yaptığımızda sorun yok.

In [24]:
np.stack([a,b]) # default axis=0

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
np.stack([a,b], axis=1) #set axis=1

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Splitting

array'leri bölerken kullanılır verilen indekslere göre böler. Listelerde de işe yarıyor.

In [40]:
a = np.array([34,35,36,37,38,39,40,41,42,43,44])

In [41]:
b,c,d = np.split(a,[2,5])
print(b)
print(c)
print(d)

[34 35]
[36 37 38]
[39 40 41 42 43 44]


In [39]:
#Liste üzerinde deneme:
l = [34,35,36,37,38,39,40,41,42,43,44]
np.split(l,[2,5])   #Sonuö olarak yine array döndürüyor.

[array([34, 35]), array([36, 37, 38]), array([39, 40, 41, 42, 43, 44])]

## vsplit

In [60]:
e = np.arange(20).reshape(2,10)
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [61]:
np.vsplit(e, [1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

## hsplit

In [67]:
e = np.arange(20).reshape(2,10)
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [69]:
np.hsplit(e, [4])

[array([[ 0,  1,  2,  3],
        [10, 11, 12, 13]]),
 array([[ 4,  5,  6,  7,  8,  9],
        [14, 15, 16, 17, 18, 19]])]

In [71]:
print(np.hsplit(e, [4])[0].shape)
print(np.hsplit(e, [4])[1].shape)

(2, 4)
(2, 6)


In [76]:
x,y,z = np.hsplit(e, [3,6])
print(x)
print(y)
print(z)

[[ 0  1  2]
 [10 11 12]]
[[ 3  4  5]
 [13 14 15]]
[[ 6  7  8  9]
 [16 17 18 19]]


In [77]:
a=np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# Sort ve argsort

**Sort** elemanları sıralar ve array'i döndürür, **argsort** elemanları sıralar ama sıralanan elemanların orjinal arraydeki indekslerini döndürür.

In [95]:
a = np.array([1,4,1,5,32,5,3,5,6,7,2])

In [96]:
np.sort(a) #yeniden atama gerekli.

array([ 1,  1,  2,  3,  4,  5,  5,  5,  6,  7, 32])

In [97]:
a.sort() # inplace yaptı direkt.
a

array([ 1,  1,  2,  3,  4,  5,  5,  5,  6,  7, 32])

In [98]:
a = np.array([1,4,1,5,32,5,3,5,6,7,2])
a.argsort()

array([ 0,  2, 10,  6,  1,  3,  5,  7,  8,  9,  4], dtype=int64)